"""
Hugging Face Spaces entry point: a Gradio chat over the same RAG pipeline.

Free Spaces only run the Gradio SDK, so this wraps the existing search() and
answer_question() - the functions POST /chat calls - rather than the React UI.
Nothing about retrieval or answering is different here.

    python app.py      # local test on http://localhost:7861
"""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "backend"))

# A Space has no .env, and config.py defaults to bge-m3. The shipped index was
# built with bge-small, so pin both here; real env vars still take precedence.
os.environ.setdefault("EMBEDDING_MODEL", "BAAI/bge-small-en-v1.5")
os.environ.setdefault("QDRANT_LOCAL_INDEX", str(ROOT / "data" / "index_export"))

import gradio as gr  # noqa: E402

from app.config import get_settings  # noqa: E402
from app.rag.answer import answer_question  # noqa: E402
from app.rag.embed import get_embeddings  # noqa: E402
from app.rag.store import IndexMismatchError, get_store, search  # noqa: E402
from app.schemas import ChatRequest  # noqa: E402

# Load the embedding model and the index before the first question, so the
# first visitor does not wait ~30s for both.
get_embeddings().embed_query("warmup")
get_store()

EXAMPLES = [
    "What was TCS's revenue in FY 2024?",
    "What was Infosys's operating margin in fiscal 2023?",
    "How did HDFC Bank's cost to income ratio change in FY24?",
    "Who audits Infosys's financial statements?",
    "What will Infosys's revenue be next year?",
]

DESCRIPTION = (
    "Ask about the FY23 and FY24 annual reports of **TCS**, **Infosys** and "
    "**HDFC Bank**. Every answer cites the filing and page it came from; the "
    "system refuses forecasts, investment advice, and questions the filings "
    "cannot answer. Answers are generated by `gpt-oss-120b` on Groq's free tier, "
    "so there is a shared daily limit. Figures from tables can occasionally be "
    "misread - check the cited page."
)


def respond(message: str, history: list) -> str:
    if not get_settings().groq_api_key:
        return "This Space has no `GROQ_API_KEY` secret configured, so it cannot answer."
    try:
        request = ChatRequest(question=message)
        response = answer_question(request, search(request))
    except IndexMismatchError as exc:
        return f"Index problem: {exc}"
    except Exception as exc:  # noqa: BLE001 - most often the free-tier rate limit
        if "rate" in str(exc).lower() or "429" in str(exc):
            return "The free-tier model limit has been reached. Please try again later."
        return f"Something went wrong: {type(exc).__name__}"

    if not response.citations:
        return response.answer

    sources = "\n".join(
        f"- **{c.company.upper()} {c.fiscal_year}** {c.doc_type.replace('_', ' ')}, "
        f"page {c.page}"
        for c in response.citations
    )
    return f"{response.answer}\n\n**Sources**\n{sources}"


demo = gr.ChatInterface(
    respond,
    title="FilingsIQ - cited Q&A over Indian company filings",
    description=DESCRIPTION,
    examples=EXAMPLES,
    cache_examples=False,
)

if __name__ == "__main__":
    demo.launch(server_port=int(os.environ.get("PORT", 7861)))
